# ========================================
# Development Profile
# ========================================

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    ma.mawa3id: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
